### ISSUE TITLE
Instructions refer to a non-existing docker repo (trickstercache/trickster)

### ISSUE THREAD

**Issue by marco-m-pix4d** [trickstercache/trickster#577]
Hello,

from the README, section [Docker](https://github.com/trickstercache/trickster#docker):

```
$ docker run --name trickster -d -v /path/to/trickster.yaml:/etc/trickster/trickster.yaml -p 0.0.0.0:8480:8480
trickstercache/trickster
```

But repo `trickstercache/trickster` doesn't exist:

```
$ docker pull trickstercache/trickster
Using default tag: latest
Error response from daemon: pull access denied for trickstercache/trickster, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

while the old one, `tricksterio/trickster`, is still there:

```
$ docker pull tricksterio/trickster
Using default tag: latest
latest: Pulling from tricksterio/trickster
801bfaa63ef2: Pull complete 
73474d244a35: Pull complete 
0404a8e5a813: Pull complete 
Digest: sha256:c6cbeee1651c78d479a08f3779e036e5d8e469d909bb78901c83e02121d4bfdf
Status: Downloaded newer image for tricksterio/trickster:latest
docker.io/tricksterio/trickster:latest
```

**Comment by jranson** [comment]
Hey Marco, thanks for pointing this out, I really appreciate the report, and am sorry I didn't get back to address it sooner.  As part of the move to the CNCF, we are in the process of changing the project handle over to `trickstercache` everywhere, including the Docker org. But that premature update was likely just an oversight in the gigantic search/replace we did on `main` as part of the ongoing migration. I am hoping to get everything switched over by the end of this week, and will let you know when the new org is good to go in Docker.

**Comment by jranson** [comment]
@marco-m-pix4d  All fixed up, sorry about the wait!

**Comment by marco-m-pix4d** [comment]
thanks @jranson, I appreciate the follow-up :-)
