### ISSUE TITLE
Inconsistent property naming for healthcheck config: `path` vs `upstream_path`

### ISSUE THREAD

**Issue by nkuba** [trickstercache/trickster#617]
The codebase and documentation are inconsistent regarding the path property for health check configuration.

The documentation mentions a `path` property in the YAML config file:
https://github.com/trickstercache/trickster/blob/41e385bee239eecbe05e1301fa0fe9931bb124b2/docs/health.md?plain=1#L53
Same as the `Options` struct:
https://github.com/trickstercache/trickster/blob/41e385bee239eecbe05e1301fa0fe9931bb124b2/pkg/backends/healthcheck/options/options.go#L58

On the other hand, `Overlay` function looks for `upstream_path` to be configured in the YAML config file:
https://github.com/trickstercache/trickster/blob/41e385bee239eecbe05e1301fa0fe9931bb124b2/pkg/backends/healthcheck/options/options.go#L132
When I grep the codebase for `upstream_path` I can see that unit tests are using this property.

As a result, a custom configuration is not read correctly from the config file.

As a workaround, to get a custom path working I had to configure both `path` and `upstream_path` properties in the config file:
```yaml
    healthcheck:
      path: /prometheus/-/ready
      upstream_path: /prometheus/-/ready
```

**Comment by jranson** [comment]
@nkuba Thanks for reporting this. We've patched it up and `main` should be good to go.
