### ISSUE TITLE
Logger not flushed before exitFatal()

### ISSUE THREAD

**Issue by tamalsaha** [trickstercache/trickster#627]
https://github.com/trickstercache/trickster/blob/2eeb4ba048ed1676105cf954c849a39278ce38cc/pkg/proxy/listener/listener.go#L185-L189

This calls `f()` to exitFatal() but the log message does not show on the terminal as the loggers are not flushed. I wasted an hour trying to understand why the program won't start. Turns out I had a `port already bind` issue from a previous run but the log message won't print and since exitFatal() does not show stack trace there is no way to know what happened.

**Comment by jranson** [comment]
@tamalsaha thanks for this report! we have merged a patch #629 to fix this up
