### ISSUE TITLE
trickster alb panic

### ISSUE THREAD

**Issue by togear** [trickstercache/trickster#667]
trickster panic when I test its alb roudrobin function
I want trickster work just like nginx proxy
-------------------------------------------
2023/05/16 10:19:16 http: panic serving 127.0.0.1:55564: unaligned 64-bit atomic operation
goroutine 84 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1854 +0xe0
panic({0x8911800, 0x8b0bfc8})
	/usr/local/go/src/runtime/panic.go:890 +0x220
runtime/internal/atomic.panicUnaligned()
	/usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Xadd64(0xa006254, 0x1)
	/usr/local/go/src/runtime/internal/atomic/atomic_386.s:125 +0x11
github.com/trickstercache/trickster/v2/pkg/backends/alb/pool.nextRoundRobin(0xa006230)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/backends/alb/pool/round_robin.go:31 +0x77
github.com/trickstercache/trickster/v2/pkg/backends/alb/pool.(*pool).Next(0xa006230)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/backends/alb/pool/pool.go:86 +0x23
github.com/trickstercache/trickster/v2/pkg/backends/alb.(*Client).handleRoundRobin(0x9f20fc0, {0xef74e1d0, 0x9c7f6b0}, 0x9f3a580)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/backends/alb/round_robin.go:30 +0x2f
net/http.HandlerFunc.ServeHTTP(0x9c127a0, {0xef74e1d0, 0x9c7f6b0}, 0x9f3a580)
	/usr/local/go/src/net/http/server.go:2122 +0x34
github.com/trickstercache/trickster/v2/pkg/encoding/handler.HandleCompression.func1({0x8b0f910, 0x9c28ea0}, 0x9f3a500)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/encoding/handler/handler.go:55 +0x2b7
net/http.HandlerFunc.ServeHTTP(0x9c10a50, {0x8b0f910, 0x9c28ea0}, 0x9f3a500)
	/usr/local/go/src/net/http/server.go:2122 +0x34
github.com/trickstercache/trickster/v2/pkg/util/middleware.WithResourcesContext.func1({0x8b0f910, 0x9c28ea0}, 0x9f3a480)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/util/middleware/config_context.go:56 +0x5eb
net/http.HandlerFunc.ServeHTTP(0x9c7e720, {0x8b0f910, 0x9c28ea0}, 0x9f3a480)
	/usr/local/go/src/net/http/server.go:2122 +0x34
github.com/trickstercache/trickster/v2/pkg/util/middleware.Decorate.func1({0x8b0fbe8, 0x9f38320}, 0x9f3a480)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/util/middleware/metrics.go:38 +0xf6
net/http.HandlerFunc.ServeHTTP(0x9c7e750, {0x8b0fbe8, 0x9f38320}, 0x9f3a480)
	/usr/local/go/src/net/http/server.go:2122 +0x34
github.com/trickstercache/trickster/v2/pkg/router.(*router).ServeHTTP(0x9c00300, {0x8b0fbe8, 0x9f38320}, 0x9f3a380)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/router/router.go:216 +0x1d1
github.com/trickstercache/trickster/v2/pkg/proxy/handlers.(*SwitchHandler).ServeHTTP(0xa0102d0, {0x8b0fbe8, 0x9f38320}, 0x9f3a380)
	/home/huang/go/src/github.com/trickstercache/trickster/pkg/proxy/handlers/switch.go:43 +0x85
net/http.serverHandler.ServeHTTP({0x9f38280}, {0x8b0fbe8, 0x9f38320}, 0x9f3a380)
	/usr/local/go/src/net/http/server.go:2936 +0x293
net/http.(*conn).serve(0x9ec22a0, {0x8b10174, 0x9c28df8})
	/usr/local/go/src/net/http/server.go:1995 +0x66d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3089 +0x498

and this is the config file i used to test
------------

frontend:
  listen_port: 80

backends:
  node-alb:
    provider: alb
    hosts:
      - www.test.com
      - localhost
    path_routing_disabled: true # only route to the alb via the foo.example.com Host header
    alb:
      mechanism: nlm  # round robin
      pool:
        - node01 # as named above
        - node02
        - node03
    healthcheck:
      path: /c.txt
      timeout_ms: 1000      # timeout_ms should be <= interval_ms
      # for ALB integration:
      interval_ms: 10000     # auto-poll health every 1s
      failure_threshold: 3  # backend is unhealthy after 3 consecutive failures
      recovery_threshold: 3 # backend is healthy after 3 consecutive successes
      expected_codes: [ 200, 204, 206, 301, 302, 304, 404]

  node01:
    provider: reverseproxy  # will cache responses to the default memory cache
    path_routing_disabled: true # disables frontend request routing via /node01 path
    origin_url: http://localhost:8080 # make requests with TLS
    healthcheck:
      path: /c.txt
      timeout_ms: 1000      # timeout_ms should be <= interval_ms
      interval_ms: 10000     # auto-poll health every 1s
      failure_threshold: 3  # backend is unhealthy after 3 consecutive failures
      recovery_threshold: 3 # backend is healthy after 3 consecutive successes
      expected_codes: [ 200, 204, 206, 301, 302, 304, 404]

  node02:
    provider: reverseproxy # requests will be proxy-only with no caching
    path_routing_disabled: true # disables frontend request routing via /node02 path
    origin_url: http://localhost:8081 # make unsecured requests
    healthcheck:
      path: /c.txt
      timeout_ms: 1000      # timeout_ms should be <= interval_ms
      interval_ms: 10000     # auto-poll health every 1s
      failure_threshold: 3  # backend is unhealthy after 3 consecutive failures
      recovery_threshold: 3 # backend is healthy after 3 consecutive successes
      expected_codes: [ 200, 204, 206, 301, 302, 304, 404]

  node03:
    provider: reverseproxy      # requests will be proxy-only with no caching
    path_routing_disabled: true # disables frontend request routing via /node02 path
    origin_url: http://localhost:8082 # make unsecured requests
    healthcheck:
      path: /c.txt
      timeout_ms: 1000      # timeout_ms should be <= interval_ms
      interval_ms: 10000     # auto-poll health every 1s
      failure_threshold: 3  # backend is unhealthy after 3 consecutive failures
      recovery_threshold: 3 # backend is healthy after 3 consecutive successes
      expected_codes: [ 200, 204, 206, 301, 302, 304, 404]

caches:
  default:
    provider: filesystem

  filesystem:
     cache_path: /tmp/trickster

metrics:
  listen_port: 8481   # available for scraping at http://<trickster>:<metrics.listen_port>/metrics

logging:
  log_level: debug

**Comment by jakenichols2719** [comment]
Trickster is using a function in the `sync/atomic` package to increment round-robin choices that is unsafe on some hardware. I'm going to work on a quick fix for this--in the meantime, could you please let me know what hardware you're running Trickster on, so I can further evaluate the problem you're experiencing?

**Comment by togear** [comment]
thank you for the reply.
I test Using Centos7 on VMware 15.5.0.
go version go1.20.4 linux/386

about cpu info
lscpu 
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    1
Socket(s):             4
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 61
Model name:            Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
Stepping:              4
CPU MHz:               2194.922
BogoMIPS:              4389.84
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              3072K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx rdtscp lm constant_tsc arch_perfmon nopl tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 movbe popcnt aes hypervisor lahf_lm 3dnowprefetch pti arat

hope this is useful.

**Comment by jakenichols2719** [comment]
That's fantastic, thank you! I don't have a VMWare setup handy, but first thing tomorrow I'm going to get to reproducing this error so we can really get to the bottom of it. In the meantime, I put in a PR that should move us towards fixing this issue. Once I have a CentOS setup running, I can test before/after the change and see if it helps!

**Comment by jakenichols2719** [comment]
Togear, #669 has been merged in and should resolve the issue you were having. We identified and fixed an atomic function that has some issues on specific hardware, which is where your error log came from; however, we weren't able to replicate, so I'll keep this issue open and closely monitored for a while in case you have further issues. Let us know if you need any more assistance!

**Comment by togear** [comment]
thanks for rapid and excellent response. 
I pull the newest code make build it and  replicate my operation again.  the panic never happen.
I think this issue is resolved now

**Comment by togear** [comment]
closed
